Repository pluralsh/deployment-operator, pull requests merged in 2023-09, with the labels that each got.

#33 Add operator helm chart
  helm/.helmignore
  helm/Chart.yaml
  helm/templates/_helpers.tpl
  helm/templates/deployment.yaml
  helm/templates/rbac.yaml
  helm/templates/secret.yaml
  helm/templates/serviceaccount.yaml
  helm/values.yaml
  helm/values.yaml.liquid
Labels: enhancement

#43 fix: proper chart versioning
  charts/deployment-operator/Chart.yaml
Labels: size/XS

#45 feat: Add checksum to operator deployment
  Dockerfile
  charts/deployment-operator/Chart.yaml
  charts/deployment-operator/templates/deployment.yaml
  cmd/main.go
  go.mod
  go.sum
  pkg/manifests/template/raw.go
  pkg/sync/constants.go
  pkg/sync/loop.go
Labels: size/M

#47 Improve resource pruning
  pkg/sync/loop.go
Labels: enhancement, size/XS

#44 ci: setup semantic release
  .github/workflows/ci.yaml
  .github/workflows/semantic-pr.yaml
  .releaserc
Labels: size/L

#49 feat: Resolve lint issues
  .github/workflows/publish.yaml
  pkg/sync/loop.go
  pkg/sync/predicates.go
  pkg/sync/status.go
Labels: enhancement, size/S
