Repository pluralsh/deployment-operator, pull requests merged in 2023-11, with the labels that each got.

#73 feat: Avoid version coercion in components
  pkg/manifests/versions.go
  pkg/sync/loop.go
  pkg/sync/status.go
Labels: enhancement, size/M

#77 feat: Reconfigure chart-releaser to have more direct tag names
  .github/configs/cr.yaml
  .github/workflows/publish.yaml
  charts/deployment-operator/Chart.yaml
Labels: enhancement, size/M

#74 feat: Show progressive delete results
  pkg/sync/loop.go
  pkg/sync/status.go
Labels: enhancement, size/S

#78 feat: introduce helm dependency update
  go.mod
  go.sum
  pkg/manifests/template/helm.go
Labels: size/L

#79 feat: Add basic scrapes for runtime services
  go.mod
  go.sum
  pkg/agent/agent.go
  pkg/client/cluster.go
  pkg/sync/engine.go
  pkg/sync/scraper.go
Labels: enhancement, size/M

#80 feat: Release v0.3.27
  charts/deployment-operator/Chart.yaml
Labels: enhancement, size/XS

#81 fix: delete logic
  pkg/sync/status.go
Labels: size/S

#82 feat: Add helm values files list support
  go.mod
  go.sum
  pkg/manifests/template/helm.go
Labels: enhancement, size/M

#83 Release v0.3.28
  charts/deployment-operator/Chart.yaml
Labels: enhancement, size/XS
