Repository pluralsh/deployment-operator, pull requests merged in 2023-10, with the labels that each got.

#50 feat: basic namespace management
  .github/workflows/ci.yaml
  pkg/manifests/template/helm.go
  pkg/sync/loop.go
Labels: size/XS

#57 add multi concurrency
  go.mod
  go.sum
  pkg/sync/loop.go
Labels: size/M

#60 Convert Agent back to an operator
  charts/deployment-operator/templates/deployment.yaml
  cmd/main.go
  go.mod
  go.sum
  pkg/agent/agent.go
Labels: size/L

#62 feat: cli-utils
  go.mod
  go.sum
  pkg/agent/agent.go
  pkg/manifests/cache.go
  pkg/manifests/template/helm.go
  pkg/manifests/template/raw.go
  pkg/manifests/template/template.go
  pkg/sync/constants.go
  pkg/sync/diff.go
  pkg/sync/engine.go
  pkg/sync/health.go
  pkg/sync/kube.go
  pkg/sync/loop.go
  pkg/sync/predicates.go
  pkg/sync/resource.go
  pkg/sync/status.go
  pkg/sync/utils.go
Labels: size/XXL

#68 feat: Implement websocket notifications to agent
  cmd/main.go
  go.mod
  go.sum
  pkg/agent/agent.go
  pkg/websocket/socket.go
Labels: enhancement, size/L

#69 feat: fix service deletion
  pkg/agent/agent.go
  pkg/sync/engine.go
  pkg/sync/loop.go
  pkg/sync/status.go
Labels: size/L

#70 feat: Bust service cache on incoming websocket
  pkg/agent/agent.go
  pkg/client/cache.go
  pkg/websocket/socket.go
Labels: size/S
