Repository pluralsh/deployment-operator, pull requests merged in 2023-12, with the labels that each got.

#84 feat: Use better socket keepalive logic
  go.mod
  go.sum
  pkg/websocket/socket.go
Labels: size/S

#85 feat: change DeletePropagationPolicy
  pkg/sync/loop.go
Labels: size/XS

#87 feat: Add expected error handling and some other tweaks
  go.mod
  go.sum
  pkg/client/service.go
  pkg/errors/base.go
  pkg/errors/manifests.go
  pkg/manifests/tarball.go
  pkg/sync/loop.go
  pkg/sync/status.go
Labels: enhancement, size/M

#89 feat: More robust wss publisher interface
  pkg/agent/agent.go
  pkg/agent/publisher.go
  pkg/manifests/cache.go
  pkg/sync/loop.go
  pkg/websocket/socket.go
Labels: size/M

#88 Bump to 0.3.29
  charts/deployment-operator/Chart.yaml
Labels: enhancement, size/XS

#90 feat: Release v0.3.30
  charts/deployment-operator/Chart.yaml
  pkg/websocket/socket.go
Labels: size/XS

#92 feat: Improve cli-utils manifest reader logic
  pkg/agent/agent.go
  pkg/manifests/template/common.go
  pkg/manifests/template/helm.go
  pkg/manifests/template/reader.go
Labels: size/L

#91 feat: release v0.4.2
  charts/deployment-operator/Chart.yaml
Labels: enhancement, size/XS

#93 feat: Begin working on communicating canary status via agent
  go.mod
  go.sum
  pkg/agent/agent.go
  pkg/applier/builder.go
  pkg/applier/filters/crd_filter.go
  pkg/applier/runner.go
  pkg/sync/engine.go
  pkg/sync/health.go
  pkg/sync/loop.go
  pkg/sync/status.go
Labels: enhancement, size/XXL

#98 feat: setup unit tests
  Makefile
  go.mod
  go.sum
  pkg/manifests/template/raw_test.go
  pkg/manifests/template/suite_test.go
  test/raw/pod.yaml
  tools.go
Labels: size/L

#97 feat: Special case CRDs in dependency filter
  pkg/applier/filters/dependency_filter.go
  pkg/applier/runner.go
Labels: enhancement, size/L

#99 feat: Don't fail on unknown gvks to avoid weird discovery client issues
  .github/workflows/ci.yaml
  pkg/manifests/template/common.go
Labels: enhancement, size/XS
