Repository pluralsh/deployment-operator, pull requests merged in 2024-04, with the labels that each got.

#158 fix: pipeline gate operator
  api/v1alpha1/pipelinegate_types.go
  charts/deployment-operator/crds/deployments.plural.sh_pipelinegates.yaml
  config/crd/bases/deployments.plural.sh_customhealths.yaml
  config/crd/bases/deployments.plural.sh_pipelinegates.yaml
  internal/controller/pipelinegate_controller.go
Labels: bug, size/XXL

#157 feat: add namespace agent
  cmd/agent.go
  go.mod
  go.sum
  pkg/client/console.go
  pkg/client/namespace.go
  pkg/controller/namespaces/reconciler.go
  pkg/controller/namespaces/socket_publisher.go
Labels: enhancement, size/L

#160 fix: Fix manifest reader inefficiency
  pkg/controller/service/reconciler.go
  pkg/manifests/template/cache.go
  pkg/manifests/template/common.go
  pkg/manifests/template/raw.go
  pkg/manifests/template/reader.go
Labels: bug, size/M, hotfix

#162 fix: respect Service.SyncConfig.NamespaceMetadata
  go.mod
  go.sum
  internal/utils/kubernetes.go
  internal/utils/maps.go
  pkg/controller/namespaces/reconciler.go
  pkg/controller/service/reconciler.go
Labels: enhancement, size/L

#163 feat: helm template with --dry-run=server
  charts/deployment-operator/templates/deployment.yaml
  charts/deployment-operator/values.yaml
  charts/deployment-operator/values.yaml.liquid
  cmd/options.go
  pkg/manifests/template/cache.go
  pkg/manifests/template/helm.go
Labels: size/S

#165 fix: Add cluster metadata fetch
  go.mod
  go.sum
  pkg/manifests/template/raw.go
Labels: enhancement, size/XS

#168 feat: Support .tpl extensions for values files
  pkg/manifests/template/helm.go
  pkg/manifests/template/tpl.go
Labels: enhancement, size/M

#167 docs: add CRD docs
  Makefile
  config.yaml
  docs/api.md
  go.mod
  go.sum
  tools.go
Labels: documentation, size/L

#173 feat: Support plumbing helm release name into agent
  go.mod
  go.sum
  pkg/manifests/template/helm.go
Labels: enhancement, size/S, hotfix

#175 feat: Invert arg order for many liquid filters
  pkg/manifests/template/raw.go
  pkg/manifests/template/utils.go
Labels: enhancement, size/S, hotfix

#177 fix: Custom implement ternary + default
  pkg/manifests/template/raw.go
  pkg/manifests/template/utils.go
Labels: enhancement, size/M, hotfix
