Repository pluralsh/deployment-operator, pull requests merged in 2024-05, with the labels that each got.

#180 feat: Better policy constraint data fetch
  internal/controller/constraint_controller.go
Labels: enhancement, size/S

#181 feat: Add constraint enforcement
  go.mod
  go.sum
  internal/controller/constraint_controller.go
Labels: enhancement, size/M

#183 fix: Bundle data description is actually keyed with
  go.mod
  go.sum
  internal/controller/constraint_controller.go
Labels: bug, size/S

#184 fix: For incomprehensible reasons, google stringifies this data field
  internal/controller/constraint_controller.go
Labels: enhancement, size/XS

#186 feat: add helm capabilities API versions
  cmd/agent.go
  go.mod
  go.sum
  pkg/controller/service/reconciler.go
  pkg/manifests/template/helm.go
Labels: enhancement, size/M

#187 fix: Kevin/eng 2022 investigate tpl values templates
  .gitignore
  README.md
  go.mod
  go.sum
  pkg/manifests/template/helm_test.go
  pkg/manifests/template/tpl_test.go
  test/tpl/_simpleConfigMap.tpl
  test/tpl/_templateWithInclude.tpl
Labels: size/L

#171 feat(harness): add stackrun harness
  .github/workflows/ci.yaml
  .github/workflows/publish-harness.yaml
  .gitignore
  Dockerfile
  Makefile
  cmd/agent/agent.go
  cmd/agent/main.go
  cmd/agent/options.go
  cmd/harness/args/args.go
  cmd/harness/main.go
  docker.mk
  hack/harness/base.Dockerfile
  hack/harness/terraform.Dockerfile
  internal/controller/stackrunjob_controller.go
  internal/helpers/buffer.go
  internal/helpers/env.go
  internal/helpers/fetch.go
  internal/helpers/fetch_types.go
  internal/helpers/file.go
  internal/helpers/http.go
  pkg/client/console.go
  pkg/client/stack.go
  pkg/errors/manifests.go
  pkg/harness/controller/controller.go
  pkg/harness/controller/controller_options.go
  pkg/harness/controller/controller_types.go
  pkg/harness/controller/executor.go
  pkg/harness/controller/executor_options.go
  pkg/harness/controller/executor_types.go
  pkg/harness/environment/environment.go
  pkg/harness/environment/environment_options.go
  pkg/harness/environment/environment_types.go
  pkg/harness/environment/version.go
  pkg/harness/errors/error.go
  pkg/harness/exec/exec.go
  pkg/harness/exec/exec_options.go
  pkg/harness/exec/exec_types.go
  pkg/harness/signals/context.go
  pkg/harness/signals/signal.go
  pkg/harness/signals/signal_handler.go
  pkg/harness/signals/signal_types.go
  pkg/harness/sink/console.go
  pkg/harness/sink/console_options.go
  pkg/harness/sink/console_types.go
  pkg/harness/stackrun/types.go
  pkg/harness/tool/ansible/ansible.go
  pkg/harness/tool/ansible/ansible_types.go
  pkg/harness/tool/ansible/modifier.go
  pkg/harness/tool/terraform/api/v4/state.go
  pkg/harness/tool/terraform/modifier.go
  pkg/harness/tool/terraform/modifier_types.go
  pkg/harness/tool/terraform/terraform.go
  pkg/harness/tool/terraform/terraform_types.go
  pkg/harness/tool/tool.go
  pkg/harness/tool/v1/modifier.go
  pkg/harness/tool/v1/types.go
  pkg/log/level.go
  pkg/test/mocks/Client_mock.go
Labels: size/XXL

#189 fix: Fix image inference for stack runs
  .github/workflows/publish-harness.yaml
  charts/deployment-operator/templates/deployment.yaml
  pkg/controller/stacks/job.go
Labels: enhancement, size/S, hotfix

#191 fix: Fix and add test for getContainerImage
  .github/workflows/publish-harness.yaml
  dockerfiles/harness/base.Dockerfile
  dockerfiles/harness/terraform.Dockerfile
  pkg/controller/stacks/job.go
  pkg/controller/stacks/job_test.go
Labels: enhancement, size/L, hotfix

#193 fix: Do not require approval to create stack run jobs
  pkg/controller/stacks/reconciler.go
  pkg/controller/stacks/reconciler_test.go
Labels: bug, size/S

#195 fix: harness image name generation
  pkg/controller/stacks/job.go
  pkg/controller/stacks/job_test.go
Labels: size/S

#194 feat(harness): support approval flow and more
  cmd/harness/main.go
  pkg/controller/stacks/reconciler.go
  pkg/harness/controller/controller.go
  pkg/harness/controller/controller_hooks.go
  pkg/harness/controller/controller_options.go
  pkg/harness/controller/controller_types.go
  pkg/harness/controller/executor.go
  pkg/harness/controller/executor_options.go
  pkg/harness/controller/executor_types.go
  pkg/harness/exec/exec.go
  pkg/harness/exec/exec_options.go
  pkg/harness/exec/exec_types.go
  pkg/harness/stackrun/types.go
  pkg/harness/tool/ansible/ansible.go
  pkg/harness/tool/terraform/terraform.go
  pkg/harness/tool/v1/types.go
Labels: size/L

#196 feat: Properly handle all controller errors
  cmd/harness/main.go
  dockerfiles/harness/base.Dockerfile
  go.mod
  go.sum
  internal/controller/stackrunjob_controller.go
  pkg/client/console.go
  pkg/client/stack.go
  pkg/controller/stacks/job.go
  pkg/harness/controller/controller.go
  pkg/harness/controller/controller_hooks.go
  pkg/harness/controller/controller_types.go
  pkg/harness/controller/executor.go
  pkg/harness/controller/executor_options.go
  pkg/harness/controller/executor_types.go
  pkg/harness/environment/environment.go
  pkg/harness/environment/environment_options.go
  pkg/harness/environment/environment_types.go
  pkg/harness/exec/exec.go
  pkg/harness/exec/exec_options.go
  pkg/harness/exec/exec_types.go
  pkg/harness/stackrun/helpers.go
  pkg/harness/stackrun/v1/types.go
  pkg/harness/tool/terraform/modifier.go
  pkg/harness/tool/terraform/modifier_types.go
  pkg/harness/tool/terraform/terraform.go
  pkg/test/mocks/Client_mock.go
Labels: enhancement, size/L

#198 fix: Fix filepath setup
  dockerfiles/harness/base.Dockerfile
  internal/helpers/env.go
  internal/helpers/file.go
  pkg/harness/controller/controller.go
  pkg/harness/environment/environment.go
  pkg/harness/tool/terraform/modifier.go
Labels: enhancement, size/M

#201 feat: set jobRef on stack run
  go.mod
  go.sum
  pkg/controller/stacks/job.go
  pkg/controller/stacks/reconciler_test.go
Labels: enhancement, size/S

#200 fix: use terraform show to get state instead of reading local file
  pkg/harness/tool/terraform/terraform.go
  pkg/harness/tool/terraform/terraform_types.go
Labels: size/S

#202 fix: harness tf state struct and state upload
  pkg/harness/tool/terraform/api/v4/state.go
  pkg/harness/tool/terraform/terraform.go
Labels: size/M

#203 feat(harness): add support for tf plural managed state
  .github/workflows/publish-harness.yaml
  cmd/harness/main.go
  go.mod
  go.sum
  pkg/harness/controller/controller.go
  pkg/harness/controller/controller_hooks.go
  pkg/harness/controller/controller_options.go
  pkg/harness/controller/controller_types.go
  pkg/harness/stackrun/v1/types.go
  pkg/harness/tool/ansible/ansible.go
  pkg/harness/tool/terraform/templates/_override.tf.gotmpl
  pkg/harness/tool/terraform/terraform.go
  pkg/harness/tool/terraform/terraform_templates.go
  pkg/harness/tool/terraform/terraform_types.go
  pkg/harness/tool/v1/types.go
Labels: size/L
