Repository pluralsh/deployment-operator, pull requests merged in 2024-06, with the labels that each got.

#205 fix: Fix binding of plural creds
  pkg/harness/stackrun/v1/types.go
Labels: enhancement, size/XS, hotfix

#209 feat(harness): add proper timeout handling for stack run step
  cmd/harness/args/args.go
  cmd/harness/main.go
  pkg/harness/controller/controller.go
  pkg/harness/controller/controller_hooks.go
  pkg/harness/controller/controller_options.go
  pkg/harness/controller/controller_types.go
  pkg/harness/exec/exec.go
  pkg/harness/exec/exec_options.go
  pkg/harness/exec/exec_types.go
  pkg/harness/tool/ansible/ansible.go
  pkg/harness/tool/terraform/terraform_types.go
Labels: enhancement, size/M

#207 feat: Kevin build Ansible harness image
  .github/workflows/publish-harness.yaml
  dockerfiles/harness/ansible.Dockerfile
  go.mod
  go.sum
Labels: size/L

#211 chore: add emptyDir mounted on /tmp for operator and agentk
  charts/deployment-operator/templates/deployment.yaml
Labels: size/XS

#213 fix: Kevin prod 2140 build ansible harness image
  dockerfiles/harness/ansible.Dockerfile
Labels: size/S

#210 feat(harness): add ansible support to harness
  Makefile
  dockerfiles/harness/ansible.Dockerfile
  pkg/harness/controller/controller.go
  pkg/harness/exec/exec.go
  pkg/harness/exec/exec_options.go
  pkg/harness/exec/exec_types.go
  pkg/harness/tool/ansible/ansible.go
  pkg/harness/tool/ansible/ansible_types.go
  pkg/harness/tool/ansible/modifier.go
  pkg/harness/tool/ansible/modifier_types.go
  pkg/harness/tool/terraform/modifier.go
  pkg/harness/tool/terraform/modifier_types.go
  pkg/harness/tool/terraform/terraform.go
  pkg/harness/tool/tool.go
  pkg/harness/tool/v1/modifier.go
  pkg/harness/tool/v1/tool.go
  pkg/harness/tool/v1/types.go
Labels: size/L

#216 fix: add custom step output scanner with error detection
  go.mod
  go.sum
  pkg/harness/controller/controller.go
  pkg/harness/controller/controller_hooks.go
  pkg/harness/exec/analyzer.go
  pkg/harness/exec/analyzer_heuristic.go
  pkg/harness/exec/analyzer_types.go
  pkg/harness/exec/exec.go
  pkg/harness/exec/exec_options.go
  pkg/harness/exec/exec_types.go
Labels: bug, size/L

#222 fix: do not allow discovery api call for helm templating to stop the agent
  cmd/agent/agent.go
  cmd/agent/options.go
  internal/helpers/poll.go
  pkg/controller/service/reconciler.go
Labels: size/M

#223 feat: scrape minimum kubelet version from k8s nodes
  pkg/ping/build.go
  pkg/ping/pinger.go
Labels: enhancement, size/M

#220 feat: add argo rollouts resume support
  cmd/agent/main.go
  go.mod
  go.sum
  internal/controller/argorollout_controller.go
  internal/utils/argorollout.go
  pkg/controller/service/health.go
  pkg/controller/service/reconciler_status.go
  pkg/controller/service/status_collector.go
Labels: enhancement, size/L

#225 feat: make a configurable poll interval
  cmd/agent/agent.go
  pkg/controller/controller.go
  pkg/controller/controller_manager.go
  pkg/controller/namespaces/reconciler.go
  pkg/controller/pipelinegates/reconciler.go
  pkg/controller/restore/reconciler.go
  pkg/controller/service/reconciler.go
  pkg/controller/stacks/job_test.go
  pkg/controller/stacks/reconciler.go
  pkg/controller/stacks/reconciler_test.go
  pkg/test/mocks/Client_mock.go
Labels: enhancement, size/M

#226 feat: integrate prometheus metrics handler and expose basic metrics
  cmd/agent/metrics.go
  go.mod
  go.sum
  internal/metrics/metrics_prometheus.go
  internal/metrics/metrics_types.go
  pkg/controller/namespaces/socket_publisher.go
  pkg/controller/service/reconciler.go
  pkg/controller/stacks/job.go
  pkg/controller/stacks/socket_publisher.go
Labels: enhancement, size/L

#228 fix: correctly traverse state module tree
  go.mod
  go.sum
  pkg/harness/controller/controller_hooks.go
  pkg/harness/signals/signal.go
  pkg/harness/tool/terraform/api/state.go
  pkg/harness/tool/terraform/api/v4/state.go
  pkg/harness/tool/terraform/terraform.go
Labels: size/L
