Repository pluralsh/deployment-operator, pull requests merged in 2024-07, with the labels that each got.

#227 feat: Agent server-side apply (SSA) deduplication cache
  .github/workflows/ci.yaml
  .github/workflows/publish.yaml
  Dockerfile
  Makefile
  charts/deployment-operator/templates/deployment.yaml
  charts/deployment-operator/values.yaml
  charts/deployment-operator/values.yaml.liquid
  cmd/agent/agent.go
  cmd/agent/args/args.go
  cmd/agent/args/pprof.go
  cmd/agent/main.go
  cmd/agent/metrics.go
  cmd/agent/options.go
  go.mod
  go.sum
  internal/controller/argorollout_controller.go
  internal/controller/customhealth_controller.go
  internal/controller/customhealth_controller_test.go
  internal/controller/pipelinegate_controller_test.go
  internal/controller/stackrunjob_controller_test.go
  internal/controller/status_controller.go
  internal/controller/suite_test.go
  internal/helpers/kubernetes.go
  internal/kstatus/watcher/common.go
  internal/kstatus/watcher/event_funnel.go
  internal/kstatus/watcher/object_status_reporter.go
  internal/kstatus/watcher/task_manager.go
  internal/kstatus/watcher/unschedulable.go
  internal/kstatus/watcher/watcher.go
  internal/kstatus/watcher/watcher_reference.go
  internal/kstatus/watcher/watcher_types.go
  internal/kubernetes/watcher/retry_lister_watcher.go
  internal/kubernetes/watcher/retry_lister_watcher_options.go
  internal/kubernetes/watcher/retry_watcher.go
  internal/metrics/metrics_context.go
  internal/metrics/metrics_options.go
  internal/metrics/metrics_prometheus.go
  internal/metrics/metrics_types.go
  internal/utils/hash.go
  pkg/applier/builder.go
  pkg/applier/filters/cache_filter.go
  pkg/applier/runner.go
  pkg/cache/cache.go
  pkg/cache/common.go
  pkg/cache/resource_cache.go
  pkg/cache/resource_cache_entry.go
  pkg/cache/resource_key.go
  pkg/common/common.go
  pkg/common/health.go
  pkg/common/lua.go
  pkg/common/status.go
  pkg/controller/controller_manager.go
  pkg/controller/service/reconciler.go
  pkg/controller/service/reconciler_status.go
  pkg/controller/service/status_collector.go
  pkg/manifests/cache.go
  pkg/manifests/tarball.go
  pkg/manifests/template/helm.go
Labels: size/XXL

#232 fix: chown /.kube dir
  Dockerfile
Labels: enhancement, size/XS

#234 fix: Work on fix for status bug
  internal/kstatus/watcher/common.go
  internal/kstatus/watcher/object_status_reporter.go
  pkg/cache/resource_cache.go
Labels: enhancement, size/S

#236 fix: null pointer when controller can't open watcher for CRD object
  internal/kstatus/watcher/watcher_reference.go
Labels: hotfix

#235 feat: add support for enforceNamespace
  go.mod
  go.sum
  pkg/controller/service/reconciler.go
Labels: enhancement, size/M

#237 fix: retry when crd not installed
  go.mod
  go.sum
  internal/controller/scope.go
  internal/controller/status_controller.go
  internal/kstatus/watcher/event_funnel.go
  internal/kstatus/watcher/object_status_reporter.go
  internal/kstatus/watcher/watcher.go
  internal/kstatus/watcher/watcher_reference.go
  internal/kstatus/watcher/watcher_types.go
  internal/kubernetes/watcher/retry_watcher.go
  pkg/applier/builder.go
  pkg/cache/resource_cache.go
Labels: size/XL

#239 feat: add support for custom stack to harness
  go.mod
  go.sum
  pkg/harness/controller/controller.go
  pkg/harness/controller/controller_hooks.go
  pkg/harness/tool/ansible/ansible.go
  pkg/harness/tool/terraform/terraform.go
  pkg/harness/tool/tool.go
  pkg/harness/tool/v1/tool.go
Labels: size/M

#241 E2e test
  .github/workflows/e2e.yaml
  Makefile
  pkg/cache/cache_test.go
  pkg/cache/resource_cache_entry_test.go
  pkg/cache/resource_cache_test.go
  pkg/cache/suite_test.go
Labels: size/L

#243 add jitter
  .github/workflows/e2e.yaml
  cmd/agent/agent.go
  cmd/agent/args/args.go
  internal/controller/argorollout_controller.go
  internal/controller/pipelinegate_controller.go
  internal/controller/requeue.go
  internal/controller/restore_controller.go
  internal/controller/stackrunjob_controller.go
  pkg/applier/filters/cache_filter_test.go
  pkg/applier/filters/suite_test.go
  pkg/controller/controller_manager.go
Labels: size/L

#242 fix(harness): retry CompleteStackRun with less data on entity too large
  internal/errors/base.go
  pkg/harness/controller/controller.go
  pkg/harness/stackrun/helpers.go
  pkg/harness/tool/terraform/terraform.go
Labels: bug, size/M

#245 feat: remove status controller finilizer
  internal/controller/status_controller.go
Labels: enhancement, size/M

#246 feat: pass reconciled revision id in service update components
  go.mod
  go.sum
  pkg/client/console.go
  pkg/client/service.go
  pkg/controller/service/reconciler_status.go
  pkg/test/mocks/Client_mock.go
Labels: enhancement, size/L
