Repository pluralsh/deployment-operator, pull requests merged in 2024-01, with the labels that each got.

#100 Extended Ping
  go.mod
  go.sum
  pkg/agent/agent.go
  pkg/client/cluster.go
  pkg/ping/build.go
  pkg/ping/distro.go
  pkg/ping/pinger.go
Labels: enhancement, size/L

#101 feat: add unit tests for helm and kustomize templates
  go.mod
  go.sum
  pkg/manifests/template/helm_test.go
  pkg/manifests/template/kustomize_test.go
  pkg/manifests/template/suite_test.go
  test/kustomize/base/deployment.yaml
  test/kustomize/base/kustomization.yaml
  test/kustomize/overlays/dev/deployment_env.yaml
  test/kustomize/overlays/dev/kustomization.yaml
Labels: size/L

#104 feat: release v0.4.3
  .github/workflows/publish.yaml
  charts/deployment-operator/Chart.yaml
Labels: size/M

#105 feat: improve crd status
  pkg/sync/health.go
  pkg/sync/status.go
Labels: enhancement, size/M

#109 feat: Add Helm labels
  pkg/manifests/template/helm.go
Labels: size/M

#106 add lua script support
  .dockerignore
  Makefile
  PROJECT
  api/v1alpha1/common_types.go
  api/v1alpha1/customhealth_types.go
  api/v1alpha1/groupversion_info.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/deployment-operator/crds/deployments.plural.sh_customhealths.yaml
  charts/deployment-operator/templates/rbac.yaml
  cmd/main.go
  config/crd/bases/deployments.plural.sh_customhealths.yaml
  config/crd/kustomization.yaml
  config/crd/kustomizeconfig.yaml
  config/rbac/role.yaml
  go.mod
  go.sum
  hack/boilerplate.go.txt
  internal/controller/customhealth_controller.go
  internal/controller/customhealth_scope.go
  internal/controller/suite_test.go
  internal/utils/kubernetes.go
  pkg/agent/agent.go
  pkg/lua/funcs.go
  pkg/lua/lua.go
  pkg/manifests/template/helm_test.go
  pkg/sync/engine.go
  pkg/sync/health.go
  pkg/sync/loop.go
  pkg/sync/status.go
Labels: size/XXL

#110 Ensure lowest version wins for runtime service shipper
  pkg/manifests/template/helm.go
  pkg/sync/scraper.go
Labels: enhancement, size/M

#111 fix: Fix github action
  .github/workflows/publish.yaml
Labels: enhancement, size/XS

#112 fix: Dockerfile
  Dockerfile
  go.mod
Labels: bug
