Repository pluralsh/deployment-operator, pull requests merged in 2024-03, with the labels that each got.

#137 feat: improve check status
  internal/controller/pipelinegate_controller.go
Labels: enhancement, size/S

#138 feat: don't set job's ttl
  pkg/client/pipelines.go
Labels: size/XS

#139 fix: don't reconcile on job changes
  internal/controller/pipelinegate_controller.go
Labels: size/XS

#142 feat: use polly lib
  go.mod
  go.sum
  internal/controller/pipelinegate_controller.go
  pkg/controller/consts.go
  pkg/controller/controller_manager.go
  pkg/controller/pipelinegates/reconciler.go
  pkg/controller/service/reconciler.go
  pkg/manifests/template/helm.go
  pkg/manifests/template/raw_test.go
Labels: enhancement, size/L

#143 feat: add CRD register controller
  charts/deployment-operator/crds/backuprepositories.yaml
  charts/deployment-operator/crds/backups.yaml
  charts/deployment-operator/crds/backupstoragelocations.yaml
  charts/deployment-operator/crds/datadownloads.yaml
  charts/deployment-operator/crds/datauploads.yaml
  charts/deployment-operator/crds/deletebackuprequests.yaml
  charts/deployment-operator/crds/downloadrequests.yaml
  charts/deployment-operator/crds/podvolumebackups.yaml
  charts/deployment-operator/crds/podvolumerestores.yaml
  charts/deployment-operator/crds/restores.yaml
  charts/deployment-operator/crds/schedules.yaml
  charts/deployment-operator/crds/serverstatusrequests.yaml
  charts/deployment-operator/crds/volumesnapshotlocations.yaml
  cmd/main.go
  internal/controller/crd_controller.go
  pkg/manifests/template/helm_test.go
Labels: enhancement, size/XXL

#145 Fix cluster casing
  pkg/manifests/template/raw.go
Labels: size/S

#146 fix: controller manager polling
  pkg/controller/controller_manager.go
  pkg/manifests/template/helm_test.go
  pkg/manifests/template/raw_test.go
Labels: bug, size/S

#147 fix: Use better namespace upsert in agent too
  internal/utils/kubernetes.go
Labels: enhancement, size/S

#150 feat: add running state to job gates
  go.mod
  go.sum
  internal/controller/pipelinegate_controller.go
Labels: enhancement, size/S

#144 feat: add constraint controller
  cmd/main.go
  go.mod
  go.sum
  internal/controller/constraint_controller.go
  pkg/client/console.go
  pkg/client/constraint.go
  pkg/manifests/template/kustomize.go
  pkg/test/mocks/Client_mock.go
Labels: size/XXL

#149 feat: Allow for single-domain kas setup
  charts/deployment-operator/templates/deployment.yaml
Labels: enhancement, size/XS

#155 feat: Add hooks to specify additional volumes and additional volume mounts
  charts/deployment-operator/templates/deployment.yaml
  charts/deployment-operator/values.yaml
Labels: enhancement, size/S
