Repository pluralsh/deployment-operator, pull requests merged in 2024-09, with the labels that each got.

#259 feat(agent): add vcluster crd and controller
  .golangci.yml
  Dockerfile
  Makefile
  api/v1alpha1/common_types.go
  api/v1alpha1/virtualcluster_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  cmd/agent/main.go
  config/crd/bases/deployments.plural.sh_customhealths.yaml
  config/crd/bases/deployments.plural.sh_pipelinegates.yaml
  config/crd/bases/deployments.plural.sh_virtualclusters.yaml
  config/rbac/role.yaml
  go.mod
  go.sum
  internal/controller/common.go
  internal/controller/virtualcluster_controller.go
  internal/controller/virtualcluster_helm.go
  internal/errors/base.go
  internal/helm/helm.go
  internal/helm/options.go
  internal/utils/kubernetes.go
  pkg/cache/user_group.go
  pkg/client/cluster.go
  pkg/client/common.go
  pkg/client/console.go
  pkg/common/common.go
  pkg/controller/stacks/reconciler_test.go
  pkg/manifests/template/helm.go
  pkg/test/mocks/Client_mock.go
  tools.go
Labels: size/XXL

#260 feat: add UpgradeInsights controller/crd
  api/v1alpha1/upgradeinsights_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  cmd/agent/main.go
  config/crd/bases/deployments.plural.sh_upgradeinsights.yaml
  docs/api.md
  go.mod
  go.sum
  internal/controller/customhealth_controller.go
  internal/controller/upgradeinsights_cloudprovider.go
  internal/controller/upgradeinsights_controller.go
  internal/controller/virtualcluster_controller.go
  internal/utils/kubernetes.go
  pkg/client/console.go
  pkg/client/upgradeinsights.go
  pkg/test/mocks/Client_mock.go
Labels: size/XXL

#262 fix: cache when error occurs
  pkg/controller/service/reconciler_status.go
Labels: size/S

#261 fix: set synced status
  pkg/common/status.go
Labels: size/XS

#263 Revert "chore(deps): bump github.com/docker/docker from 24.0.7+incompatible to 25.0.6+incompatible"
  go.mod
  go.sum
Labels: size/S

#258 feat: kustomize services with liquid templating
  pkg/manifests/template/kustomize.go
  pkg/manifests/template/kustomize_test.go
  test/kustomize/liquid/dev/deployment_env.yaml
  test/kustomize/liquid/dev/kustomization.yaml.liquid
Labels: size/L

#271 fix(harness): fix tf variables length check
  pkg/harness/tool/terraform/terraform.go
Labels: size/XS

#272 fix: clear cache entry when `status == ApplyFailed`
  pkg/controller/service/reconciler_status.go
Labels: size/S, hotfix

#268 feat: Ingress replica CRD
  api/v1alpha1/ingressreplica_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/deployment-operator/crds/deployments.plural.sh_ingressreplicas.yaml
  cmd/agent/kubernetes.go
  config/crd/bases/deployments.plural.sh_ingressreplicas.yaml
  internal/controller/ingressreplica_controller.go
  internal/controller/ingressreplica_controller_test.go
  pkg/manifests/template/helm_test.go
Labels: size/XL

#270 feat: add console manager supervisor logic w/ restart option
  cmd/agent/args/args.go
  cmd/agent/args/pprof.go
  cmd/agent/console.go
  cmd/agent/kubernetes.go
  cmd/agent/main.go
  internal/controller/argorollout_controller.go
  internal/controller/customhealth_controller.go
  internal/controller/customhealth_controller_test.go
  internal/controller/pipelinegate_controller.go
  internal/controller/pipelinegate_controller_test.go
  internal/metrics/metrics_prometheus.go
  internal/metrics/metrics_types.go
  pkg/cache/discovery_cache.go
  pkg/cache/gate_cache.go
  pkg/cache/resource_cache.go
  pkg/client/cache.go
  pkg/common/common.go
  pkg/common/status.go
  pkg/controller/common/consts.go
  pkg/controller/controller.go
  pkg/controller/controller_manager.go
  pkg/controller/controller_manager_options.go
  pkg/controller/namespaces/reconciler.go
  pkg/controller/pipelinegates/reconciler.go
  pkg/controller/pipelinegates/socket_publisher.go
  pkg/controller/restore/reconciler.go
  pkg/controller/service/reconciler.go
  pkg/controller/service/reconciler_scraper.go
  pkg/controller/service/reconciler_status.go
  pkg/controller/service/status_collector.go
  pkg/controller/stacks/job.go
  pkg/controller/stacks/reconciler.go
  pkg/controller/v1/types.go
  pkg/log/zap.go
Labels: size/XXL

#283 fix: CI github action
  .github/workflows/ci.yaml
Labels: bug, size/M

#269 feat: metrics aggregate
  .mockery.yaml
  Makefile
  api/v1alpha1/metricsaggregate_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/deployment-operator/crds/deployments.plural.sh_metricsaggregates.yaml
  cmd/agent/kubernetes.go
  cmd/agent/main.go
  config/crd/bases/deployments.plural.sh_metricsaggregates.yaml
  config/samples/metricsAggregate.yaml
  go.mod
  go.sum
  internal/controller/debounce_controller.go
  internal/controller/metricsaggregate.go
  internal/controller/metricsaggregate_controller_test.go
  internal/controller/suite_test.go
  pkg/manifests/template/helm_test.go
  pkg/test/mocks/DiscoveryInterface_mock.go
  tools.go
Labels: size/XXL

#285 fix(upgradeinsights): use ec2imds region resolver to create aws client
  internal/controller/upgradeinsights_cloudprovider.go
Labels: size/XS

#290 fix: metricsaggregate sporadic errors
  cmd/agent/kubernetes.go
  cmd/agent/main.go
  internal/controller/metricsaggregate.go
Labels: size/M, hotfix
