Repository pluralsh/deployment-operator, pull requests merged in 2024-10, with the labels that each got.

#289 fix: Pass deploy token to run jobs through secret
  cmd/agent/args/args.go
  cmd/harness/args/args.go
  go.mod
  pkg/controller/stacks/job.go
  pkg/controller/stacks/secret.go
Labels: size/L

#292 fix: Use job spec namespace if it is available
  cmd/agent/console.go
  cmd/agent/main.go
  internal/utils/kubernetes.go
  pkg/controller/stacks/job.go
  pkg/controller/stacks/job_test.go
  pkg/controller/stacks/reconciler.go
  pkg/controller/stacks/reconciler_test.go
  pkg/controller/stacks/secret.go
Labels: bug, size/L

#293 feat: add resource requests into stack run jobs
  go.mod
  go.sum
  pkg/controller/stacks/job.go
  pkg/controller/stacks/job_test.go
Labels: size/L

#296 feat(upgradeinsights): add support for warning status
  go.mod
  go.sum
  internal/controller/upgradeinsights_cloudprovider.go
Labels: size/S

#295 fix: helm templating
  pkg/cache/discovery_cache.go
  pkg/manifests/template/helm_test.go
  pkg/manifests/template/suite_test.go
  test/crd/monitoring.coreos.com_servicemonitors.yaml
  test/helm/yet-another-cloudwatch-exporter/Chart.yaml
  test/helm/yet-another-cloudwatch-exporter/templates/_helpers.tpl
  test/helm/yet-another-cloudwatch-exporter/templates/servicemonitor.yaml
  test/helm/yet-another-cloudwatch-exporter/values.yaml
Labels: bug, size/XXL

#298 feat(upgradeinsights): add client stats support to upgrade insights
  go.mod
  go.sum
  internal/controller/upgradeinsights_cloudprovider.go
Labels: size/S

#300 feat: resolve imports from services
  go.mod
  go.sum
  pkg/manifests/template/raw.go
  pkg/manifests/template/tpl.go
  pkg/manifests/template/utils.go
  pkg/manifests/template/utils_test.go
Labels: enhancement, size/M

#301 feat: reconcile helm resources with hooks + set a healthy state as a default for CRD without a condition block
  go.mod
  go.sum
  pkg/common/health.go
  pkg/common/health_test.go
  pkg/common/suite_test.go
  pkg/manifests/template/helm.go
  pkg/manifests/template/helm_test.go
  test/helm/yet-another-cloudwatch-exporter/templates/job.yaml
Labels: enhancement, size/L

#302 fix: metrics aggregate controller
  .mockery.yaml
  internal/controller/metricsaggregate.go
  internal/controller/metricsaggregate_controller_test.go
  pkg/test/mocks/Interface_mock.go
  pkg/test/mocks/MetricsV1beta1Interface_mock.go
  pkg/test/mocks/NodeMetricsInterface_mock.go
Labels: size/XL, hotfix

#304 test: add controler's unit tests
  pkg/common/health_test.go
  pkg/controller/namespaces/reconciler_test.go
  pkg/controller/namespaces/suite_test.go
  pkg/controller/restore/reconciler_test.go
  pkg/controller/restore/suite_test.go
Labels: size/L

#306 feat: strip down cluster and service sideloads
  go.mod
  go.sum
  internal/controller/argorollout_controller.go
  pkg/client/console.go
  pkg/client/service.go
  pkg/controller/service/reconciler.go
  pkg/test/mocks/Client_mock.go
Labels: enhancement, size/L

#307 feat: Add AI insight component scraper
  cmd/agent/main.go
  go.mod
  go.sum
  pkg/common/health.go
  pkg/ping/build.go
  pkg/scraper/component_scraper.go
Labels: enhancement, size/L
