Repository pluralsh/deployment-operator, pull requests merged in 2024-02, with the labels that each got.

#114 refactor: Agent refactoring
  .mockery.yaml
  Dockerfile
  Makefile
  charts/deployment-operator/crds/backuprepositories.yaml
  charts/deployment-operator/crds/backups.yaml
  charts/deployment-operator/crds/backupstoragelocations.yaml
  charts/deployment-operator/crds/datadownloads.yaml
  charts/deployment-operator/crds/datauploads.yaml
  charts/deployment-operator/crds/deletebackuprequests.yaml
  charts/deployment-operator/crds/downloadrequests.yaml
  charts/deployment-operator/crds/podvolumebackups.yaml
  charts/deployment-operator/crds/podvolumerestores.yaml
  charts/deployment-operator/crds/restores.yaml
  charts/deployment-operator/crds/schedules.yaml
  charts/deployment-operator/crds/serverstatusrequests.yaml
  charts/deployment-operator/crds/volumesnapshotlocations.yaml
  cmd/agent.go
  cmd/main.go
  cmd/options.go
  config/crd/bases/deployments.plural.sh_services.yaml
  go.mod
  go.sum
  internal/controller/backup_controller.go
  internal/controller/customhealth_controller.go
  internal/errors/base.go
  internal/utils/kubernetes.go
  pkg/agent/agent.go
  pkg/agent/ratelimiting.go
  pkg/applier/builder.go
  pkg/client/cache.go
  pkg/client/cluster.go
  pkg/client/console.go
  pkg/client/restore.go
  pkg/client/service.go
  pkg/controller/controller.go
  pkg/controller/controller_manager.go
  pkg/controller/restore/reconciler.go
  pkg/controller/restore/socket_publisher.go
  pkg/controller/service/health.go
  pkg/controller/service/reconciler.go
  pkg/controller/service/reconciler_scraper.go
  pkg/controller/service/reconciler_status.go
  pkg/controller/service/socket_publisher.go
  pkg/controller/service/status_collector.go
  pkg/lua/lua_test.go
  pkg/lua/suite_test.go
  pkg/manifests/cache.go
  pkg/manifests/template/helm_test.go
  pkg/ping/pinger.go
  pkg/sync/constants.go
  pkg/sync/engine.go
  pkg/sync/kube.go
  pkg/sync/loop.go
  pkg/sync/status.go
  pkg/test/mocks/Client_mock.go
  pkg/websocket/socket.go
  test/lua/test.lua
Labels: size/XXL

#108 feat: add dry run support
  pkg/controller/service/reconciler.go
  pkg/controller/service/reconciler_status.go
  pkg/controller/service/status_collector.go
Labels: enhancement, size/L

#116 add custom health controller unit tests
  internal/controller/customhealth_controller_test.go
  internal/controller/suite_test.go
  pkg/lua/suite_test.go
Labels: size/L

#117 Minimal deployment operator change
  charts/deployment-operator/Chart.yaml
  charts/deployment-operator/templates/deployment.yaml
  charts/deployment-operator/values.yaml
  go.mod
  go.sum
  pkg/manifests/template/helm.go
Labels: enhancement, size/M

#107 feat: gate-operator
  .github/workflows/lint-and-test.yml
  .gitignore
  api/v1alpha1/doc.go
  api/v1alpha1/pipelinegate_types.go
  api/v1alpha1/register.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/deployment-operator/Chart.yaml
  charts/deployment-operator/crds/deployments.plural.sh_pipelinegates.yaml
  charts/deployment-operator/templates/rbac.yaml
  charts/deployment-operator/values.yaml
  cmd/agent.go
  cmd/main.go
  config/crd/bases/deployments.plural.sh_customhealths.yaml
  config/crd/bases/deployments.plural.sh_pipelinegates.yaml
  config/crd/bases/pipelines.plural.sh_pipelinegates.yaml
  config/rbac/pipelines_pipelinegate_editor_role.yaml
  config/rbac/pipelines_pipelinegate_viewer_role.yaml
  config/rbac/role.yaml
  config/samples/pipeline_cr.yaml
  config/samples/pipelines.yaml
  config/samples/pipelines2.yaml
  config/samples/pipelines3.yaml
  config/samples/pipelines_v1alpha1_pipelinegate.yaml
  go.mod
  go.sum
  internal/controller/pipelinegate_controller.go
  internal/controller/pipelinegate_scope.go
  internal/utils/kubernetes.go
  pkg/client/console.go
  pkg/client/pipelines.go
  pkg/controller/pipelinegates/reconciler.go
  pkg/controller/pipelinegates/socket_publisher.go
  pkg/controller/restore/reconciler.go
  pkg/controller/service/reconciler.go
  pkg/lua/suite_test.go
  pkg/manifests/template/helm_test.go
Labels: size/XXL

#119 feat: Begin working on sideloading contexts
  internal/utils/kubernetes.go
  pkg/client/pipelines.go
  pkg/manifests/template/raw.go
Labels: enhancement, size/S

#118 feat: avoid fetching components for ServiceDeployment
  cmd/agent.go
  cmd/options.go
  go.mod
  go.sum
  internal/controller/customhealth_scope.go
  internal/utils/kubernetes.go
  pkg/applier/runner.go
  pkg/client/console.go
  pkg/client/service.go
  pkg/controller/service/kubernetes.go
  pkg/controller/service/reconciler.go
  pkg/controller/service/reconciler_status.go
  pkg/controller/service/socket_publisher.go
  pkg/controller/service/status_collector.go
  pkg/manifests/cache.go
  pkg/manifests/template/helm.go
  pkg/manifests/template/helm_test.go
  pkg/manifests/template/kustomize.go
  pkg/manifests/template/kustomize_test.go
  pkg/manifests/template/raw.go
  pkg/manifests/template/raw_test.go
  pkg/manifests/template/template.go
  pkg/manifests/template/utils.go
Labels: enhancement, size/L

#120 feat: implement paginated polling agent-side
  go.mod
  go.sum
  pkg/client/console.go
  pkg/client/pipelines.go
  pkg/client/service.go
  pkg/controller/pipelinegates/reconciler.go
  pkg/controller/service/reconciler.go
  pkg/manifests/template/raw.go
  pkg/manifests/template/utils.go
  pkg/test/mocks/Client_mock.go
Labels: enhancement, size/L

#121 feat: push image to docker registry
  .github/workflows/ci.yaml
  .github/workflows/publish.yaml
Labels: enhancement, size/S

#125 feat: Reduce some unnecessary logging
  pkg/controller/pipelinegates/reconciler.go
  pkg/controller/service/reconciler.go
  pkg/controller/service/reconciler_status.go
Labels: size/S

#122 feat: Refactor gate operator
  api/v1alpha1/pipelinegate_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/deployment-operator/crds/deployments.plural.sh_pipelinegates.yaml
  cmd/agent.go
  cmd/main.go
  config/crd/bases/deployments.plural.sh_pipelinegates.yaml
  go.mod
  internal/controller/pipelinegate_controller.go
  internal/utils/hash.go
  internal/utils/kubernetes.go
  pkg/client/console.go
  pkg/client/pipelines.go
  pkg/controller/controller.go
  pkg/controller/pipelinegates/reconciler.go
  pkg/controller/service/reconciler.go
  pkg/manifests/cache.go
  pkg/manifests/tarball.go
  pkg/manifests/untar.go
  pkg/websocket/socket.go
Labels: size/XL

#127 feat: tune service deletion
  internal/errors/base.go
  pkg/controller/service/reconciler.go
Labels: enhancement, size/M

#129 feat: Add more sprig funcs
  pkg/manifests/template/raw.go
Labels: size/XS

#133 fix: Don't sideload jobs in pipeline gate queries
  go.mod
  go.sum
  pkg/client/pipelines.go
Labels: enhancement, size/S

#135 feat: refactor gate operator
  api/v1alpha1/pipelinegate_types.go
  internal/controller/job_scope.go
  internal/controller/pipelinegate_controller.go
  internal/utils/kubernetes.go
  pkg/client/pipelines.go
  pkg/controller/pipelinegates/reconciler.go
Labels: enhancement, size/XL
