Repository pluralsh/deployment-operator, pull requests merged in 2024-12, with the labels that each got.

#317 fix: Vuln extraction
  .github/workflows/lint-and-test.yml
  go.mod
  go.sum
  internal/controller/vulnerabilityreports_controller.go
Labels: enhancement, size/M, hotfix

#319 chore: improve Vulnerability Report Reconciler
  internal/controller/vulnerabilityreports_controller.go
Labels: enhancement, size/XS

#322 fix: Bump chart to 0.5.0
  charts/deployment-operator/Chart.yaml
Labels: bug, size/XS, hotfix

#323 fix: Rework kubecost extractor for in-cluster deployment
  internal/controller/kubecostextractor_controller.go
Labels: enhancement, size/M, hotfix

#324 feat: get node and control plane costs
  cmd/agent/args/args.go
  cmd/agent/kubernetes.go
  cmd/agent/main.go
  go.mod
  go.sum
  internal/controller/kubecostextractor_controller.go
Labels: size/L

#327 fix: Change kubecost window param
  internal/controller/kubecostextractor_controller.go
Labels: bug, size/XS, hotfix

#329 fix: Include idle node costs
  internal/controller/kubecostextractor_controller.go
Labels: bug, size/S, hotfix

#331 fix: post empty lists for insightComponents
  pkg/ping/build.go
Labels: enhancement, size/XS

#326 fix: Prod 3036/fix ansible docker image
  .github/workflows/publish-harness-fips.yaml
  .github/workflows/publish-harness.yaml
  dockerfiles/harness/ansible.Dockerfile
  dockerfiles/harness/ansible.fips.Dockerfile
Labels: bug, size/XL

#334 fix: update golang.org/x/net package to non-vulnerable version
  go.mod
  go.sum
Labels: size/M

#335 chore: Update docs
  .github/workflows/docs.yaml
  .github/workflows/e2e.yaml
  Makefile
  docs/api.md
Labels: enhancement, size/L
