Repository pluralsh/deployment-operator, pull requests merged in 2024-08, with the labels that each got.

#249 feat: update container image generation for stacks
  .github/workflows/ci.yaml
  go.mod
  go.sum
  internal/controller/customhealth_controller.go
  internal/utils/kubernetes.go
  pkg/controller/service/reconciler_status.go
  pkg/controller/stacks/job.go
  pkg/controller/stacks/job_test.go
  pkg/controller/stacks/reconciler_test.go
  tools.go
Labels: enhancement, size/XL

#250 fix(harness): improve exec with output logging
  pkg/harness/tool/terraform/terraform.go
Labels: bug, size/XS

#251 feat(harness): add stackrun variables support to terraform
  go.mod
  go.sum
  internal/helpers/env.go
  pkg/harness/controller/controller.go
  pkg/harness/stackrun/v1/types.go
  pkg/harness/tool/ansible/ansible.go
  pkg/harness/tool/ansible/ansible_types.go
  pkg/harness/tool/ansible/modifier.go
  pkg/harness/tool/ansible/modifier_types.go
  pkg/harness/tool/terraform/terraform.go
  pkg/harness/tool/terraform/terraform_types.go
  pkg/harness/tool/tool.go
Labels: enhancement, size/M

#253 fix: Handle nil variables properly
  pkg/harness/tool/terraform/terraform.go
Labels: enhancement, size/XS, hotfix

#257 feat: check pending job's Pod
  internal/controller/stackrunjob_controller.go
Labels: enhancement, size/S
