Repository pluralsh/deployment-operator, pull requests merged in 2025-07, with the labels that each got.

#481 fix: Bump polly to v0.3.1
  go.mod
  go.sum
Labels: bug, size/XS, hotfix

#486 chore: bump polly to v0.3.2
  go.mod
  go.sum
  pkg/manifests/template/helm.go
Labels: dependencies, size/M

#489 feat: add additional cluster fields to ping requests
  cmd/agent/kubernetes.go
  cmd/agent/main.go
  internal/controller/metricsaggregate.go
  internal/controller/metricsaggregate_controller_test.go
  pkg/cache/db/cache.go
  pkg/cache/db/cache_test.go
  pkg/cache/db/queries.go
  pkg/common/k8s.go
  pkg/ping/build.go
  pkg/ping/pinger.go
  pkg/scraper/metrics.go
Labels: enhancement, size/XL

#490 feat: openshift distro discovery
  cmd/agent/main.go
  go.mod
  go.sum
  pkg/common/k8s.go
  pkg/controller/pipelinegates/reconciler.go
  pkg/controller/service/reconciler.go
  pkg/ping/build.go
  pkg/ping/pinger.go
Labels: enhancement, size/M

#498 fix: az inference
  pkg/ping/pinger.go
Labels: bug, size/XS, hotfix
