Repository pluralsh/deployment-operator, pull requests merged in 2025-06, with the labels that each got.

#453 feat: use SQLite store to gather cluster insight components
  cmd/agent/main.go
  go.mod
  go.sum
  pkg/cache/db/cache.go
  pkg/cache/db/cache_test.go
  pkg/cache/db/queries.go
  pkg/cache/resource_cache.go
  pkg/common/resources.go
  pkg/common/status.go
  pkg/controller/service/reconciler_scraper.go
  pkg/ping/build.go
  pkg/scraper/component_scraper.go
  pkg/scraper/servergroups.go
Labels: enhancement, size/XL

#455 fix: terraform parallelism implementation
  pkg/harness/controller/controller.go
  pkg/harness/stackrun/v1/types.go
  pkg/harness/tool/terraform/modifier.go
  pkg/harness/tool/terraform/modifier_types.go
  pkg/harness/tool/terraform/terraform.go
  pkg/harness/tool/terraform/terraform_types.go
  pkg/harness/tool/v1/types.go
Labels: bug, size/M

#459 fix: Don't send pods in cluster component insights
  pkg/cache/db/cache_test.go
  pkg/cache/db/queries.go
Labels: enhancement, size/S

#460 chore: bump polly to v0.2.3
  go.mod
  go.sum
Labels: dependencies, size/XS

#462 fix: lua merge order
  go.mod
  go.sum
  pkg/manifests/template/helm.go
  pkg/manifests/template/helm_test.go
  pkg/manifests/template/raw.go
Labels: enhancement, size/M

#463 chore: detect splitbrain
  Dockerfile
  charts/deployment-operator/templates/deployment.yaml
  pkg/manifests/cache.go
  pkg/manifests/tarball.go
  pkg/manifests/tarball_test.go
Labels: enhancement, size/M

#466 fix: Improve update status for Job
  pkg/controller/service/reconciler_status.go
Labels: size/XS, hotfix

#467 fix: bump polly
  go.mod
  go.sum
Labels: enhancement, size/XS

#464 fix: Fix cluster health score query
  pkg/cache/db/cache_test.go
  pkg/cache/db/queries.go
Labels: size/L

#468 fix: Improve resource cache crd detection
  go.mod
  go.sum
  internal/controller/crd_controller.go
  pkg/applier/filters/cache_filter.go
  pkg/cache/resource_cache.go
  pkg/cache/resource_key.go
  pkg/manifests/cache.go
  pkg/manifests/template/helm.go
  pkg/scraper/servergroups.go
Labels: bug, size/L

#470 fix: Drop aquasecurity groups
  pkg/cache/resource_cache.go
  pkg/common/k8s.go
  pkg/scraper/servergroups.go
Labels: size/M

#472 fix: set default status for error
  pkg/harness/controller/controller.go
Labels: size/XS, hotfix

#474 chore: bump polly to v0.2.9
  go.mod
  go.sum
Labels: enhancement

#473 fix: save manifest sha only if the resource was successfully applied
  pkg/applier/filters/cache_filter.go
  pkg/applier/filters/cache_filter_test.go
  pkg/cache/resource_cache.go
  pkg/cache/resource_cache_entry.go
  pkg/cache/resource_cache_entry_test.go
  pkg/controller/service/reconciler_status.go
Labels: size/M

#476 fix: remove the incorrect error message
  pkg/cache/resource_cache.go
Labels: hotfix
