Repository pluralsh/deployment-operator, pull requests merged in 2025-01, with the labels that each got.

#332 chore: reduce deployment operator logging
  pkg/cache/resource_cache.go
  pkg/controller/service/reconciler.go
  pkg/controller/service/reconciler_status.go
Labels: enhancement, size/S

#339 feat: add recommendation filtering
  api/v1alpha1/kubecostextractor_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/deployment-operator/crds/deployments.plural.sh_kubecostextractors.yaml
  config/crd/bases/deployments.plural.sh_kubecostextractors.yaml
  config/samples/kubecostExtractor.yaml
  internal/controller/kubecostextractor_controller.go
  internal/controller/kubecostextractor_controller_test.go
Labels: enhancement, size/L

#346 feat: Add cpu util/memory util to recommendations extractor
  go.mod
  go.sum
  internal/controller/kubecostextractor_controller.go
Labels: enhancement, size/XS

#347 feat: add certificates to cluster insight component scraper
  cmd/agent/main.go
  go.mod
  go.sum
  internal/controller/kubecostextractor_controller.go
  internal/controller/kubecostextractor_controller_test.go
  pkg/scraper/component_scraper.go
Labels: enhancement, size/L

#350 chore: bump agentk version in helm chart
  charts/deployment-operator/values.yaml
Labels: size/XS

#353 chore: sideload cluster distro by agent
  go.mod
  go.sum
  pkg/manifests/template/utils.go
Labels: enhancement, size/M

#354 feat: extend service cluster context with console dns
  cmd/agent/args/args.go
  cmd/agent/main.go
  pkg/manifests/template/utils.go
Labels: size/S

#355 fix: respec jobSpec.resources for pipelines
  pkg/client/pipelines.go
  pkg/controller/stacks/job.go
Labels: hotfix

#356 feat: extend eks upgrade insights with addons information
  go.mod
  go.sum
  internal/controller/upgradeinsights_cloudprovider.go
  internal/controller/upgradeinsights_controller.go
  pkg/client/console.go
  pkg/client/upgradeinsights.go
  pkg/harness/signals/context.go
  pkg/test/mocks/Client_mock.go
Labels: size/L

#358 fix: kubecost extractor
  internal/controller/kubecostextractor_controller.go
  pkg/cache/resource_cache_entry.go
Labels: hotfix

#360 chore: bump console go client
  go.mod
  go.sum
  pkg/client/console.go
  pkg/client/service.go
  pkg/controller/service/reconciler.go
  pkg/controller/service/reconciler_status.go
  pkg/controller/service/reconciler_test.go
  pkg/controller/service/socket_publisher.go
  pkg/controller/service/status_collector.go
  pkg/manifests/cache.go
  pkg/manifests/template/helm.go
  pkg/manifests/template/helm_test.go
  pkg/manifests/template/kustomize.go
  pkg/manifests/template/kustomize_test.go
  pkg/manifests/template/raw.go
  pkg/manifests/template/raw_test.go
  pkg/manifests/template/template.go
  pkg/manifests/template/tpl.go
  pkg/manifests/template/tpl_test.go
  pkg/manifests/template/utils.go
  pkg/manifests/template/utils_test.go
  pkg/test/mocks/Client_mock.go
Labels: enhancement, size/L
