Repository pluralsh/deployment-operator, pull requests merged in 2025-02, with the labels that each got.

#361 chore: Optimize deployment operator
  pkg/client/cache.go
  pkg/client/console.go
  pkg/client/service.go
  pkg/controller/common/consts.go
  pkg/controller/service/reconciler.go
  pkg/test/mocks/Client_mock.go
Labels: enhancement, size/M

#363 feat: add namespace inference to the runtime service fetch process
  go.mod
  go.sum
  pkg/client/cluster.go
  pkg/client/console.go
  pkg/controller/service/reconciler_scraper.go
  pkg/test/mocks/Client_mock.go
Labels: enhancement, size/L

#362 chore: optimize stack fetching in deployment operator
  .github/workflows/e2e.yaml
  go.mod
  go.sum
  pkg/client/console.go
  pkg/client/stack.go
  pkg/controller/service/reconciler_scraper.go
  pkg/controller/stacks/reconciler.go
  pkg/test/mocks/Client_mock.go
Labels: enhancement, size/M

#365 fix: go-fips
  Dockerfile
  dockerfiles/harness/base.Dockerfile
  dockerfiles/harness/base.fips.Dockerfile
  go.mod
  go.sum
Labels: size/L, hotfix

#368 chore: remove more low-signal logs and change health rules for status condition
  pkg/common/health.go
  pkg/common/health_test.go
  pkg/controller/namespaces/reconciler.go
  pkg/controller/pipelinegates/reconciler.go
  pkg/controller/service/reconciler_status.go
  pkg/controller/stacks/reconciler.go
Labels: enhancement, size/M

#370 fix: Only apply stale-if-fail health checks to whitelisted gvks
  pkg/common/common.go
  pkg/common/health.go
  pkg/common/health_test.go
Labels: bug, size/S, hotfix

#374 fix(harness): do not send an error if stack run was cancelled
  pkg/harness/controller/controller_hooks.go
Labels: size/XS

#375 feat: add digest url param to service tarball fetches
  pkg/manifests/cache.go
  pkg/manifests/cache_test.go
  pkg/manifests/tarball.go
  pkg/manifests/tarball_test.go
Labels: size/L

#373 feat: add support for trivy security scanner to harness
  cmd/harness/main.go
  dockerfiles/harness/base.Dockerfile
  dockerfiles/harness/base.fips.Dockerfile
  go.mod
  go.sum
  internal/helpers/env.go
  pkg/harness/controller/controller.go
  pkg/harness/controller/controller_hooks.go
  pkg/harness/controller/controller_types.go
  pkg/harness/security/scanner.go
  pkg/harness/security/trivy/trivy.go
  pkg/harness/security/trivy/trivy_types.go
  pkg/harness/security/v1/options_types.go
  pkg/harness/security/v1/scanner_types.go
  pkg/harness/security/v1/utils.go
  pkg/harness/stackrun/v1/types.go
  pkg/harness/tool/ansible/ansible.go
  pkg/harness/tool/terraform/terraform.go
  pkg/harness/tool/terraform/terraform_types.go
  pkg/harness/tool/tool.go
  pkg/harness/tool/v1/tool.go
  pkg/harness/tool/v1/types.go
Labels: enhancement, size/XXL

#372 feat: surface upgrade insight errors to conditions
  internal/controller/scope.go
  internal/controller/upgradeinsights_cloudprovider.go
  internal/controller/upgradeinsights_controller.go
Labels: size/M
