Repository pluralsh/deployment-operator, pull requests merged in 2025-08, with the labels that each got.

#504 chore: refactor cluster and runtime service pings
  cmd/agent/args/args.go
  cmd/agent/main.go
  pkg/controller/pipelinegates/reconciler.go
  pkg/controller/service/reconciler.go
  pkg/ping/cluster.go
  pkg/ping/pinger.go
  pkg/ping/runtime_service.go
  pkg/ping/runtime_service_test.go
  pkg/ping/suite_test.go
Labels: enhancement, size/L

#512 feat: Add a bit more manifest error logging
  pkg/manifests/tarball.go
Labels: enhancement, size/XS

#511 chore: Add GitHub confirmation that a deployed agent is available
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/semantic-pr.yaml
Labels: size/M

#505 feat: add AgentConfiguration crd
  api/v1alpha1/agentconfig_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/deployment-operator/crds/deployments.plural.sh_agentconfigurations.yaml
  cmd/agent/args/args.go
  cmd/agent/console.go
  cmd/agent/kubernetes.go
  config/crd/bases/deployments.plural.sh_agentconfigurations.yaml
  config/samples/agentConfiguration.yaml
  docs/api.md
  internal/controller/agentconfiguration_controller.go
  internal/controller/vulnerabilityreports_controller.go
  internal/controller/vulnerabilityreports_controller_test.go
  internal/helpers/poll.go
  internal/helpers/poll_test.go
  pkg/cache/discovery_cache.go
  pkg/common/config.go
  pkg/controller/controller.go
  pkg/controller/controller_manager.go
  pkg/controller/namespaces/reconciler.go
  pkg/controller/namespaces/reconciler_test.go
  pkg/controller/pipelinegates/reconciler.go
  pkg/controller/restore/reconciler.go
  pkg/controller/restore/reconciler_test.go
  pkg/controller/service/reconciler.go
  pkg/controller/service/reconciler_test.go
  pkg/controller/stacks/reconciler.go
  pkg/controller/v1/types.go
  pkg/ping/cluster.go
  pkg/ping/runtime_service.go
  pkg/scraper/metrics.go
  pkg/scraper/servergroups.go
Labels: size/XXL

#519 fix: Work on dynamic poller fixes
  internal/helpers/poll.go
  pkg/controller/controller.go
  pkg/controller/controller_manager.go
  pkg/controller/restore/reconciler.go
  pkg/controller/service/reconciler.go
Labels: bug, size/M

#521 fix: cilium compatibilities not discovered
  pkg/client/cluster.go
  pkg/ping/pinger.go
  pkg/ping/runtime_service.go
Labels: size/L
