Repository pluralsh/deployment-operator, pull requests merged in 2025-04, with the labels that each got.

#397 fix: resource health status
  cmd/agent/console.go
  cmd/agent/main.go
  internal/controller/clusterdrain_controller.go
  pkg/applier/filters/cache_filter_test.go
  pkg/cache/resource_cache.go
  pkg/cache/resource_cache_entry.go
  pkg/cache/resource_cache_test.go
  pkg/common/health_test.go
  pkg/common/status.go
  pkg/common/suite_test.go
  pkg/controller/service/reconciler.go
  pkg/controller/service/reconciler_status.go
  pkg/controller/service/reconciler_test.go
  pkg/controller/service/status_collector.go
  pkg/scraper/component_scraper.go
Labels: size/L, hotfix

#398 fix: Support `ignoreCRDs` and fix bug in debounce controller
  go.mod
  go.sum
  internal/controller/debounce_controller.go
  pkg/manifests/template/helm.go
Labels: size/S

#396 feat: cluster drain should be resilient to deployment operator pod restarts
  api/v1alpha1/clusterdrain_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/deployment-operator/crds/deployments.plural.sh_clusterdrains.yaml
  config/crd/bases/deployments.plural.sh_clusterdrains.yaml
  internal/controller/clusterdrain_controller.go
Labels: enhancement, size/L

#399 feat: add configurable liveness and readiness probes to chart
  charts/deployment-operator/templates/deployment.yaml
  charts/deployment-operator/values.yaml
Labels: size/S

#401 fix: Fix probe schemas
  charts/deployment-operator/values.yaml
Labels: size/S, hotfix

#403 fix: Revert "fix: resource health status"
  cmd/agent/console.go
  cmd/agent/main.go
  internal/controller/clusterdrain_controller.go
  pkg/applier/filters/cache_filter_test.go
  pkg/cache/resource_cache.go
  pkg/cache/resource_cache_entry.go
  pkg/cache/resource_cache_test.go
  pkg/common/health_test.go
  pkg/common/status.go
  pkg/common/suite_test.go
  pkg/controller/service/reconciler.go
  pkg/controller/service/reconciler_status.go
  pkg/controller/service/reconciler_test.go
  pkg/controller/service/status_collector.go
  pkg/scraper/component_scraper.go
Labels: bug, size/L, hotfix

#409 chore: Split builds between ARM and AMD64
  .github/workflows/ci.yaml
  .github/workflows/publish.yaml
Labels: size/L

#411 perf: deployment improvements
  cmd/agent/kubernetes.go
  pkg/common/status.go
  pkg/scraper/component_scraper.go
Labels: size/L

#413 feat: return recommendations for each pod in the parent object
  internal/controller/kubecostextractor_controller.go
Labels: enhancement, size/M

#351 fix(agent): memory leaks and optimize resource usage with Datadog/Pyroscope integrations
  .github/workflows/ci.yaml
  .golangci.yml
  api/v1alpha1/pipelinegate_types.go
  cmd/agent/args/args.go
  cmd/agent/args/datadog.go
  cmd/agent/args/pyroscope.go
  cmd/agent/console.go
  cmd/agent/kubernetes.go
  cmd/agent/main.go
  go.mod
  go.sum
  internal/controller/clusterdrain_controller.go
  internal/controller/constraint_controller.go
  internal/controller/constraint_controller_test.go
  internal/controller/ingressreplica_controller.go
  internal/controller/kubecostextractor_controller.go
  internal/controller/pipelinegate_controller.go
  internal/controller/stackrunjob_controller.go
  internal/controller/status_controller.go
  internal/controller/vulnerabilityreports_controller.go
  internal/helm/helm.go
  internal/helpers/fetch.go
  internal/kstatus/watcher/object_status_reporter.go
  internal/kstatus/watcher/watcher_reference.go
  internal/kubernetes/watcher/retry_lister_watcher.go
  internal/metrics/metrics_types.go
  internal/utils/kubernetes.go
  pkg/applier/builder.go
  pkg/cache/cache_test.go
  pkg/cache/resource_cache.go
  pkg/cache/resource_cache_test.go
  pkg/client/namespace.go
  pkg/client/pipelines.go
  pkg/client/service.go
  pkg/client/stack.go
  pkg/common/common.go
  pkg/common/health.go
  pkg/common/status.go
  pkg/controller/controller.go
  pkg/controller/service/reconciler.go
  pkg/controller/service/reconciler_scraper.go
  pkg/controller/service/reconciler_status.go
  pkg/controller/stacks/job.go
  pkg/controller/stacks/job_test.go
  pkg/harness/controller/controller_hooks.go
  pkg/lua/lua.go
  pkg/manifests/tarball.go
  pkg/manifests/template/cache.go
  pkg/manifests/template/helm.go
  pkg/manifests/untar.go
  pkg/scraper/component_scraper.go
Labels: size/XL

#416 perf: Memory usage optimisations
  internal/kubernetes/watcher/retry_lister_watcher.go
  pkg/applier/runner.go
  pkg/controller/service/reconciler.go
  pkg/manifests/cache.go
  pkg/manifests/tarball.go
  pkg/manifests/template/common.go
  pkg/manifests/template/helm.go
  pkg/manifests/template/kustomize.go
  pkg/manifests/template/raw.go
  pkg/manifests/template/reader.go
  pkg/manifests/template/template.go
  pkg/manifests/untar.go
  pkg/manifests/versions.go
Labels: size/L

#395 feat(chart): add ability to mount custom certs
  Dockerfile
  charts/deployment-operator/templates/configmap.yaml
  charts/deployment-operator/templates/deployment.yaml
  charts/deployment-operator/values.yaml
Labels: enhancement, size/M

#417 chore: update go to 1.24
  Dockerfile
  dockerfiles/agent/fips.Dockerfile
  dockerfiles/harness/ansible.Dockerfile
  dockerfiles/harness/ansible.fips.Dockerfile
  dockerfiles/harness/base.Dockerfile
  dockerfiles/harness/base.fips.Dockerfile
  go.mod
  go.sum
  internal/kubernetes/watcher/retry_lister_watcher.go
Labels: enhancement, size/L

#410 feat: Helm chart install test for deployment operator
  .github/workflows/helm-chart-install-test.yaml
  README.md
  test/helm/README.md
  test/helm/deployment-operator/Chart.yaml
  test/helm/deployment-operator/values.yaml
  test/helm/test-chart-install.sh
Labels: enhancement, size/L

#422 fix: Manifest cache jitter
  .github/CODEOWNERS
  cmd/agent/args/args.go
  cmd/agent/console.go
  internal/helpers/fetch_types.go
  pkg/client/console.go
  pkg/client/service.go
  pkg/controller/service/reconciler.go
  pkg/controller/service/reconciler_status.go
  pkg/controller/service/reconciler_test.go
  pkg/manifests/cache.go
  pkg/test/mocks/Client_mock.go
Labels: size/XL

#421 feat: Support EBPF service mesh type
  go.mod
  go.sum
  pkg/cache/discovery_cache.go
  pkg/client/cluster.go
  pkg/controller/service/reconciler_scraper.go
Labels: size/M

#418 feat: detect usage of deprecated custom resources in our agent
  cmd/agent/console.go
  pkg/client/cluster.go
  pkg/client/console.go
  pkg/controller/service/reconciler.go
  pkg/controller/service/reconciler_scraper.go
  pkg/controller/service/reconciler_scraper_test.go
  pkg/controller/service/reconciler_test.go
  pkg/controller/service/suite_test.go
  pkg/controller/v1/versions.go
  pkg/scraper/component_scraper.go
  pkg/test/mocks/Client_mock.go
  test/crd/velero.io_backups.yaml
Labels: enhancement, size/XL
