Repository pluralsh/deployment-operator, pull requests merged in 2025-05, with the labels that each got.

#424 fix: add retry, and fix panic
  go.mod
  go.sum
  internal/kubernetes/watcher/retry_watcher.go
  pkg/manifests/tarball.go
Labels: hotfix

#425 feat: add support for Helm in kustomize arguments
  go.mod
  go.sum
  pkg/manifests/template/kustomize.go
  pkg/manifests/template/kustomize_test.go
  pkg/manifests/template/utils_test.go
Labels: size/S

#426 fix: error handling
  pkg/controller/service/reconciler.go
  pkg/controller/service/reconciler_status.go
Labels: size/S, hotfix

#427 fix: add helm binary to agent container for kustomize inflate helm to work
  Dockerfile
  dockerfiles/agent/fips.Dockerfile
Labels: bug, size/S

#429 fix: Fix log message
  pkg/controller/service/reconciler_scraper.go
Labels: bug, size/XS

#430 fix: Istio addon discovery
  internal/controller/constraint_controller.go
  pkg/client/cluster.go
  pkg/client/console.go
  pkg/client/constraint.go
  pkg/controller/service/reconciler_scraper.go
  pkg/test/mocks/Client_mock.go
Labels: enhancement, size/L

#431 fix: Add more jitter to manifest caches
  cmd/agent/args/args.go
  pkg/controller/controller.go
  pkg/manifests/tarball.go
Labels: enhancement, size/S

#433 fix: Fix a panic due to bad os walk
  pkg/controller/controller.go
  pkg/manifests/template/template.go
Labels: bug, size/S, hotfix

#435 feat: Extend manifest cache duration
  cmd/agent/args/args.go
  pkg/controller/controller.go
  pkg/manifests/tarball.go
Labels: enhancement, size/M

#438 feat: Allow registry customization
  charts/deployment-operator/templates/deployment.yaml
  charts/deployment-operator/values.yaml
  charts/deployment-operator/values.yaml.liquid
Labels: enhancement, hotfix

#436 feat: add component children tree with cache
  cmd/agent/main.go
  go.mod
  go.sum
  pkg/cache/db/cache.go
  pkg/cache/db/cache_bench_test.go
  pkg/cache/db/cache_test.go
  pkg/cache/db/queries.go
  pkg/cache/db/state.go
  pkg/cache/resource_cache.go
  pkg/cache/resource_cache_entry.go
  pkg/cache/resource_cache_test.go
  pkg/cache/resource_key.go
  pkg/common/status.go
  pkg/controller/service/reconciler_status.go
  pkg/controller/service/reconciler_test.go
  pkg/controller/service/status_collector.go
Labels: size/XXL

#441 fix(db-cache): fix an issue with storing group in component cache db
  pkg/cache/db/cache_test.go
  pkg/cache/db/queries.go
Labels: bug, size/L

#440 feat: (terraform) Add support for parallelism and refresh flags
  go.mod
  go.sum
  pkg/harness/stackrun/v1/types.go
Labels: size/S

#445 fix(harness): use TF_CLI_ARGS to correctly pass tf args
  pkg/harness/stackrun/v1/types.go
Labels: bug, size/XS

#444 fix: Fix FIPS Dockerfile
  dockerfiles/agent/fips.Dockerfile
Labels: size/XS

#448 feat: Add cluster health score to pings
  go.mod
  go.sum
  pkg/cache/db/cache.go
  pkg/cache/db/cache_test.go
  pkg/cache/db/queries.go
  pkg/ping/build.go
Labels: size/M

#447 feat: Filter sensitive attributes
  pkg/harness/tool/terraform/api/state.go
  pkg/harness/tool/terraform/api/state.json
  pkg/harness/tool/terraform/api/state_test.go
Labels: size/L

#450 feat: Add node statistics
  go.mod
  go.sum
  pkg/cache/db/cache.go
  pkg/cache/db/cache_bench_test.go
  pkg/cache/db/cache_test.go
  pkg/cache/db/queries.go
  pkg/cache/resource_cache.go
  pkg/common/status.go
  pkg/controller/service/status_collector.go
  pkg/ping/build.go
Labels: enhancement, size/L

#449 fix(deployment-operator): prevent re-echoing tarball errors in reconciler
  pkg/controller/service/reconciler.go
  pkg/manifests/tarball.go
Labels: bug, size/S
