Repository pluralsh/deployment-operator, pull requests merged in 2025-03, with the labels that each got.

#380 feat(harness): add dry run support to harness
  go.mod
  go.sum
  pkg/harness/controller/controller.go
  pkg/harness/stackrun/v1/types.go
Labels: size/M

#382 fix: delete manifest cache on service delete
  pkg/controller/service/reconciler.go
  pkg/manifests/cache.go
Labels: size/XS, hotfix

#385 fix: concurrent map writes
  pkg/websocket/socket.go
Labels: size/S, hotfix

#384 fix: nil pointer exception when there are no services
  pkg/client/cluster.go
Labels: bug, size/XS, hotfix

#387 fix: always set sevice mesh if not nil
  pkg/client/cluster.go
Labels: size/S

#388 feat: add ClusterDrain resource
  .github/workflows/lint-and-test.yml
  api/v1alpha1/clusterdrain_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/deployment-operator/crds/deployments.plural.sh_clusterdrains.yaml
  charts/deployment-operator/crds/deployments.plural.sh_pipelinegates.yaml
  charts/deployment-operator/templates/rbac.yaml
  cmd/agent/kubernetes.go
  config/crd/bases/deployments.plural.sh_clusterdrains.yaml
  config/crd/bases/deployments.plural.sh_pipelinegates.yaml
  internal/controller/clusterdrain_controller.go
  internal/controller/clusterdrain_controller_test.go
Labels: enhancement, size/XXL

#389 chore: improve ClusterDrain controller
  internal/controller/clusterdrain_controller.go
Labels: enhancement, size/XS

#392 fix: fetch pods status for pending Deployment,DaemonSet and StatefulSet
  internal/controller/clusterdrain_controller.go
  internal/utils/kubernetes.go
  pkg/common/common.go
  pkg/common/health.go
  pkg/scraper/component_scraper.go
Labels: enhancement, size/L

#393 fix: always mount tmp dir to operator
  charts/deployment-operator/templates/deployment.yaml
Labels: bug, size/XS
